version: '3.1'

services:
  db:
    build: ./Docker/db/
    container_name: portfolio_meu
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./Docker/db/.:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=portfolio
